export const caseList = [
    {
        id: 0,
        type_case: 'depart',
    },
    {
        id: 1,
        type_case: 'propriete',
        nom: 'Boulevard de Belleville',
        couleur: '934828',
        proprietaire: null,
        prix:  60,
        0: 2,
        1: 10,
        2: 30,
        3: 90,
        4: 160,
        5: 250,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  50
    },
    {
        id: 2,
        type_case: 'caisseCommunaute',
    },
    {
        id: 3,
        type_case: 'propriete',
        nom: 'Rue Lecourbe',
        couleur: '934828',
        proprietaire: null,
        prix:  60,
        0: 4,
        1: 20,
        2: 60,
        3: 160,
        4: 320,
        5: 450,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  50
    },
    {
        id: 4,
        type_case: 'impotRevenu',
        nom: 'Impots sur le revenu',
        prix:  200
    },
    {
        id: 5,
        type_case: 'gare',
        nom: 'Gare Montparnasse',
        proprietaire: null,
        prix:  200,
        1: 25,
        2: 50,
        3: 100,
        4: 200
    },
    {
        id: 6,
        type_case: 'propriete',
        nom: 'Rue de Vaugirard',
        couleur: 'bae4fa',
        proprietaire: null,
        prix:  100,
        0: 6,
        1: 30,
        2: 90,
        3: 270,
        4: 400,
        5: 550,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  50
    },
    {
        id: 7,
        type_case: 'chance',
    },
    {
        id: 8,
        type_case: 'propriete',
        nom: 'Rue de Courcelles',
        couleur: 'bae4fa',
        proprietaire: null,
        prix:  100,
        0: 6,
        1: 30,
        2: 90,
        3: 270,
        4: 400,
        5: 550,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  50
    },
    {
        id: 9,
        type_case: 'propriete',
        nom: 'Avenue de la République',
        couleur: 'bae4fa',
        proprietaire: null,
        prix:  120,
        0: 8,
        1: 40,
        2: 100,
        3: 300,
        4: 450,
        5: 600,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  50
    },
    {
        id: 10,
        type_case: 'prison',
    },
    {
        id: 11,
        type_case: 'propriete',
        nom: 'Boulevard de la Villette',
        couleur: 'da2d86',
        proprietaire: null,
        prix:  140,
        0: 10,
        1: 50,
        2: 150,
        3: 450,
        4: 625,
        5: 750,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 12,
        type_case: 'compagnie',
        nom: 'Compagnie de distribution d\'éléctricité',
        proprietaire: null,
        prix:  150
    },
    {
        id: 13,
        type_case: 'propriete',
        nom: 'Avenue de Neuilly',
        couleur: 'da2d86',
        proprietaire: null,
        prix:  140,
        0: 10,
        1: 50,
        2: 150,
        3: 450,
        4: 625,
        5: 750,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 14,
        type_case: 'propriete',
        nom: 'Rue de Paradis',
        couleur: 'da2d86',
        proprietaire: null,
        prix:  160,
        0: 12,
        1: 60,
        2: 180,
        3: 500,
        4: 700,
        5: 900,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 15,
        type_case: 'gare',
        nom: 'Gare de Lyon',
        proprietaire: null,
        prix:  200,
        1: 25,
        2: 50,
        3: 100,
        4: 200
    },
    {
        id: 16,
        type_case: 'propriete',
        nom: 'Avenue Mozart',
        couleur: 'f88f02',
        proprietaire: null,
        prix:  180,
        0: 14,
        1: 70,
        2: 200,
        3: 550,
        4: 700,
        5: 900,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 17,
        type_case: 'caisseCommunaute',
    },
    {
        id: 18,
        type_case: 'propriete',
        nom: 'Boulevard Saint-Michel',
        couleur: 'f88f02',
        proprietaire: null,
        prix:  180,
        0: 14,
        1: 70,
        2: 200,
        3: 550,
        4: 700,
        5: 900,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 19,
        type_case: 'propriete',
        nom: 'Place Pigaille',
        couleur: 'f88f02',
        proprietaire: null,
        prix:  200,
        0: 16,
        1: 80,
        2: 220,
        3: 600,
        4: 800,
        5: 1000,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  100
    },
    {
        id: 20,
        type_case: 'parcGratuit',
    },
    {
        id: 21,
        type_case: 'propriete',
        nom: 'Avenue Matignon',
        couleur: 'e3010d',
        proprietaire: null,
        prix:  220,
        0: 18,
        1: 90,
        2: 250,
        3: 700,
        4: 875,
        5: 1050,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 22,
        type_case: 'chance',
    },
    {
        id: 23,
        type_case: 'propriete',
        nom: 'Boulevard Malesherbes',
        couleur: 'e3010d',
        proprietaire: null,
        prix:  220,
        0: 18,
        1: 90,
        2: 250,
        3: 700,
        4: 875,
        5: 1050,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 24,
        type_case: 'propriete',
        nom: 'Avenue Henri-Martin',
        couleur: 'e3010d',
        proprietaire: null,
        prix:  240,
        0: 20,
        1: 100,
        2: 300,
        3: 750,
        4: 925,
        5: 1100,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 25,
        type_case: 'gare',
        nom: 'Gare du Nord',
        proprietaire: null,
        prix:  200,
        1: 25,
        2: 50,
        3: 100,
        4: 200
    },
    {
        id: 26,
        type_case: 'propriete',
        nom: 'Faubourg Saint-Honoré',
        couleur: 'feec00',
        proprietaire: null,
        prix:  260,
        0: 22,
        1: 110,
        2: 330,
        3: 800,
        4: 975,
        5: 1150,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 27,
        type_case: 'propriete',
        nom: 'Place de la Bourse',
        couleur: 'feec00',
        proprietaire: null,
        prix:  260,
        0: 22,
        1: 110,
        2: 330,
        3: 800,
        4: 975,
        5: 1150,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 28,
        type_case: 'compagnie',
        nom: 'Compagnie de distribution des eaux',
        proprietaire: null,
        prix:  150
    },
    {
        id: 29,
        type_case: 'propriete',
        nom: 'Rue la Fayette',
        couleur: 'feec00',
        proprietaire: null,
        prix:  280,
        0: 24,
        1: 120,
        2: 360,
        3: 850,
        4: 1025,
        5: 1200,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  150
    },
    {
        id: 30,
        type_case: 'allerPrison',
    },
    {
        id: 31,
        type_case: 'propriete',
        nom: 'Avenue de Breteuil',
        couleur: '1fa54c',
        proprietaire: null,
        prix:  300,
        0: 26,
        1: 130,
        2: 390,
        3: 900,
        4: 1100,
        5: 1275,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  200
    },
    {
        id: 32,
        type_case: 'propriete',
        nom: 'Avenue Foch',
        couleur: '1fa54c',
        proprietaire: null,
        prix:  300,
        0: 26,
        1: 130,
        2: 390,
        3: 900,
        4: 1100,
        5: 1275,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  200
    },
    {
        id: 33,
        type_case: 'caisseCommunaute',
    },
    {
        id: 34,
        type_case: 'propriete',
        nom: 'Boulevard des Capucines',
        couleur: '1fa54c',
        proprietaire: null,
        prix:  320,
        0: 28,
        1: 150,
        2: 450,
        3: 1000,
        4: 1200,
        5: 1400,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  200
    },
    {
        id: 35,
        type_case: 'gare',
        nom: 'Gare Saint-Lazare',
        proprietaire: null,
        prix:  200,
        1: 25,
        2: 50,
        3: 100,
        4: 200,
    },
    {
        id: 36,
        type_case: 'chance',
    },
    {
        id: 37,
        type_case: 'propriete',
        nom: 'Avenue des Champs-Élysées',
        couleur: '0168b3',
        proprietaire: null,
        prix:  350,
        0: 35,
        1: 175,
        2: 500,
        3: 1100,
        4: 1300,
        5: 1500,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  200
    },
    {
        id: 38,
        type_case: 'taxeLuxe',
        nom: 'Taxe de luxe',
        proprietaire: null,
        prix:  100
    },
    {
        id: 39,
        type_case: 'propriete',
        nom: 'Rue de la Paix',
        couleur: '0168b3',
        proprietaire: null,
        prix:  400,
        0: 50,
        1: 200,
        2: 600,
        3: 1400,
        4: 1700,
        5: 2000,
        nombreMaison : 0,
        memeProprio: false,
        prixMaison:  200
    }
]